- name: Add subscriptions
  hosts: load_balancers,database_servers,app_servers
  gather_facts: true
  tasks:

    - name: install katello package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: register system and attach subscriptions
      redhat_subscription:
        state: present
        username: "admin"
        password: "r3dh4t1!"
        auto_attach: true
