---
- name: Get DB IP address with hostvars for the app servers
  hosts: database_servers
  gather_facts: true
  tags:
    - application_servers

  tasks: []

- name: Deploy, configure flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: true
  tags:
    - application_servers

  roles:
    - flask
